// Code generated by MockGen. DO NOT EDIT.
// Source: ./infrastructure/db/client_repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIClientRepository is a mock of IClientRepository interface.
type MockIClientRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIClientRepositoryMockRecorder
}

// MockIClientRepositoryMockRecorder is the mock recorder for MockIClientRepository.
type MockIClientRepositoryMockRecorder struct {
	mock *MockIClientRepository
}

// NewMockIClientRepository creates a new mock instance.
func NewMockIClientRepository(ctrl *gomock.Controller) *MockIClientRepository {
	mock := &MockIClientRepository{ctrl: ctrl}
	mock.recorder = &MockIClientRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIClientRepository) EXPECT() *MockIClientRepositoryMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockIClientRepository) Insert(ctx context.Context, client interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, client)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockIClientRepositoryMockRecorder) Insert(ctx, client interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockIClientRepository)(nil).Insert), ctx, client)
}
